services:
  - type: web
    name: msc-graphrag-demo2
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false        
